project:
  type: website
  output-dir: _site

website:
  title: "Bueller"
  description: "Chronic absenteeism analysis"
  site-url: "https://erwx.github.io/bueller/"
  navbar:
    background: primary
    title: "Bueller"
    left:
      - text: "About"
        href: about.html
      - text: "Documents"
        href: documents.qmd
      - text: "Presentations"
        href: presentations.qmd

format:
  html:
    theme: minty
