project:
  type: website
  output-dir: _site

website:
  title: "bueller"
  description: "student engagement analysis package"
  site-url: "."
  navbar:
    background: primary
    title: "bueller"
    left:
      - text: "about"
        href: about.html
      - text: "examples"
        menu:
          - text: "documents"
            href: engagement-report.html
          - text: "presentations"
            href: bueller-presentation-1.qmd

format:
  html:
    theme: minty
    toc: true