project:
  type: website
  output-dir: _site

website:
  title: "bueller"
  description: "student engagement analysis package"
  site-url: "."
  navbar:
    background: primary
    title: "bueller"
    left:
      - text: "examples"
        menu:
          - text: "documents"
            href: documents.html
          - text: "presentations"
            href: presentations.html

format:
  html:
    theme: minty
    toc: true